### ISSUE TITLE
Timeframe?

### ISSUE THREAD

**Issue by csumrell** [cmorbitzer/cordova-plugin-inapppurchase#2]
Hi Cmorbitzer,

Any timeline on when you will get around to doing some maintenance on this plugin? Hopefully soon, as my IOS customers are pissed!

Thanks

**Comment by cmorbitzer** [comment]
Before I started, I wanted to see if https://github.com/j3k0/cordova-plugin-purchase would work and it appears it does. I've been able to implement it successfully in my projects. I know the API is different and it will require some refactoring, but considering it's actively maintained and has a large community around it too, I'd recommend switching. That worked for me. If there's a reason that project doesn't work for your needs, let's talk--maybe it would be good to keep this project up.

**Comment by csumrell** [comment]
That sounds good, I will use that one. I was under the impression from the comments on Alexdisler's repo that it was also not working.
